# Generated by Django 5.2.4 on 2025-07-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="reset_code_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
